Sc myfirstchange
foundercore/VegaTestPortal pull request #9
Opened 2021-05-07 13:27 UTC by shital131

Change the Logout button and Background of a header.

2021-05-07 14:13 UTC, shital131 reviewed
Changes the Logout Button with a Circle within a image add View Profile, SignIn option in a list. And change the background color of a menu bar.

2021-05-08 05:16 UTC, shital131 commented
Revert changes in some files.

2021-05-08 07:46 UTC, shital131 commented
Add js in my code and revert  changes in header component.

2021-05-08 11:38 UTC, kunwarkundanbblock commented on src/index.html
> +     toggle between hiding and showing the circle content */
Remove this script from here.

2021-05-09 01:42 UTC, kunwarkundanbblock commented on src/app/views/user-management/user-management.component.html
> +    <!-- <div *ngFor="let user of userList" class="row">
uncomment these lines.

2021-05-09 01:42 UTC, kunwarkundanbblock requested changes
Uncomment the lines in user html

2021-05-09 04:13 UTC, merged

2021-05-09 06:39 UTC, shital131 commented
Done.

On Sun, May 9, 2021 at 9:43 AM kunwarkundanbblock ***@***.***>
wrote:

> Merged #9 <https://github.com/foundercore/VegaTestPortal/pull/9> into
> master.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/foundercore/VegaTestPortal/pull/9#event-4709727815>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AT65M5AZ53L5I3E3J5WSHJTTMYDXRANCNFSM44KABHRQ>
> .
>